########################################
# Shared
variable "name_tag_convention" {
  description = "The name tag convention of all resources."
  type = object({
    project_name = string
    stage        = string
  })
  default = {
    project_name = "tf"
    stage        = "poc"
  }
}

variable "global_additional_tag" {
  description = "Additional tags for all resources."
  type        = map(string)
  default     = {}
}
########################################

########################################
# AWS EFS
variable "name_tag_postfix" {
  description = "The postfix of name tag (e.g. `main`)"
  type        = string
  default     = ""
}

variable "availability_zone_name" {
  description = "(opt) It is used only when using 'One Zone' storage classes."
  type        = string
  default     = null
}

variable "creation_token" {
  description = "(opt) By default generated by Terraform. (Maxium of 64 characters)"
  type        = string
  default     = null
}

variable "encrypted" {
  description = "(opt) If true, the disk will be encrypted. `kms_key_id` need to be set"
  type        = bool
  default     = null
}

variable "kms_key_id" {
  description = "(opt) The arn of kms key for encrypting storage."
  type        = string
  default     = null
}

variable "performance_mode" {
  description = "(opt) Can be either`generalPurpose` or `maxIO`."
  type        = string
  default     = "generalPurpose"
}

variable "throughput_mode" {
  description = "(opt) Can be either `bursting` or `provisioned`."
  type        = string
  default     = "bursting"
}

variable "provisioned_throughput_in_mibps" {
  description = "(opt) `throughput_mode` need to be `provisioned`."
  type        = number
  default     = null
}

variable "lifecycle_policy" {
  description = "(opt) Valid value is AFTER_7_DAYS, AFTER_14_DAYS, AFTER_30_DAYS, AFTER_60_DAYS, and AFTER_90_DAYS"
  type = object({
    transition_to_ia = string
  })
  default = null
}

variable "tags" {
  description = "(opt)"
  type        = map(string)
  default     = null
}
########################################

########################################
# AWS EFS Mount
variable "subnet_ids" {
  description = "(req) The ID of the subnet to add the mount target in"
  type        = set(string)
}

variable "security_group_ids" {
  description = "(opt) Up to five VPC security group IDs"
  type        = set(string)
  default     = null
}

variable "ip_address" {
  description = "(opt) Valid IPv4 address within the address range of the specified subnet."
  type        = string
  default     = null
}
########################################